### PR TITLE
fix: start pipeline for gitlab

### PR DESCRIPTION
**Pull request by yelhouti**

### CODE REVIEW

**Comment by ankitm123** [comment]
can we add test for this? This will help us to avoid regression in the future, and give us more confidence when refactoring.

**Comment by keskad** [comment]
Would be nice to have that merged, thank you for this piece of code :smiley:

**Comment by yelhouti** [comment]
@keskad did it work for you ? Which git Provider please ?

**Comment by keskad** [comment]
I'm fighting with Gitlab provider actually.
I don't know if your fix actually is in same moment where I got stuck.

```
DEBUG: about to run: jx pipeline wait --owner root --repo testowe-repo-damian

waiting up to 20m0s for a trigger to be added to the lighthouse configuration in ConfigMap config in namespace jx for repository: root/testowe-repo-damian
you can watch the boot job to update the configuration via: jx admin log
for more information on how this works see: https://jenkins-x.io/docs/v3/about/how-it-works/#importing--creating-quickstarts
```

It seems it does not update the ConfigMap `config` at `jx` namespace, possibly it is not related. But also I don't know which component of `jx` is responsible for such update, where I should report the issue. The `jx` architecture is a little bit complex.

**Comment by yelhouti** [comment]
Slack is the best place to ask question, what do you want to do exactly ?

**Comment by keskad** [comment]
I need to import the project. Ok, I will go to slack then to not spam there with possibly unrelated issue.

**Comment by ankitm123** [comment]
See if this helps: https://jenkins-x.io/v3/admin/troubleshooting/quickstart-import/ (atleast it will give u some understanding of the steps which happen when importing a repo into JX)

**Comment by bartoliniii** [comment]
@yelhouti As we discuss on Slack, we have a similar issue but we are using Bitbucket Server:
```
error: failed to calculate in repo configuration: failed to load trigger config for repository sen/senti-bot for ref master: failed to find any lighthouse configuration files in repo sen/senti-bot at sha master: Not Supported
```

After your changes, there is small progress! 👍 
Now we got an issue that the repository is not found on our server, and indeed url generated by jx-pipeline(?) is wrong (should be https://bitbucket.our.domain/**scm/**sen/senti-bot/). It is probably correct syntax Bitbucket Cloud syntax but not for Bitbucket Server
```
ERROR: error creating a mirror clone: exit status 128 Cloning into bare repository '/var/tmp/gitcache1202549360/sen/senti-bot'...
fatal: repository 'https://bitbucket.our.domain/sen/senti-bot/' not found
error: failed to calculate in repo configuration: failed to load trigger config for repository sen/senti-bot for ref : failed to create repo client: error creating a mirror clone: exit status 128 Cloning into bare repository '/var/tmp/gitcache1202549360/sen/senti-bot'...
fatal: repository 'https://bitbucket.our.domain/sen/senti-bot/' not found
```

There is no option --git-kind to force bitbucketserver.

Do you have any idea what can we do with this issue?

**Comment by bartoliniii** [comment]
@ankitm123 I've debug a little and it seems that `gitv2.NewClientFactory(configureOpts)`  in line 457 in start.go isn't able to create the correct url for Bitbucket server (for http access). It just takes schema, url, owner and repo to build URL but Bitbucket Server needs additionaly 'scm' as path like that: https://bitbucket.company/scm/owner/repo/.

Finally, error occurs in [46 line of load_triggers.go in lighthouse-client ](https://github.com/jenkins-x/lighthouse-client/blob/main/pkg/triggerconfig/inrepo/load_triggers.go#L46) where we try to connect to https://bitbucket.company/owner/repo/ instead of https://bitbucket.company/scm/owner/repo/

**Comment by chrislovecnm** [comment]
@ankitm123 do we have the log output for this? I can help debug this.  I am hitting this bug as well.

**Comment by yelhouti** [comment]
Didn't see it was the lint I kk fix it as soon as I can

**Comment by yelhouti** [comment]
@ankitm123 could you approve this, github forgot about me

**Comment by msvticket** [comment]
golangci-lint run is failing with 

 	pkg/cmd/start/start.go:406:12: ineffectual assignment to err (ineffassign)
				gitInfo, err = giturl.ParseGitURL(gitServerURL)
				         ^

**Review by msvticket — APPROVED** [review]

**Comment by yelhouti** [comment]
@msvticket why is PR failing please ?

**Comment by msvticket** [comment]
> @msvticket why is PR failing please ?

Unfortunately there is no error message. The `go build` command just exits in the middle with the error code 255. I'll see if I can gather some more information if I monitor the pod in real time.

**Comment by msvticket** [comment]
I think the problem is that the compilation is taking so much memory that there is a big risk that the process is killed due to lack of memory on the node. I tracked the memory consumption and it peaked at 1673Mi, while the resource request is 600Mi.

This time I was lucky...

**Comment by yelhouti** [comment]
Finally !!! this was years into making XD

**Comment by yelhouti** [comment]
@msvticket thanks a lot

**Comment by msvticket** [comment]
The release failed due to a unit test failure:

```
--- FAIL: TestPipelineStart (23.86s)
		    start_test.go:237: running test file
		    start_test.go:237: running test defaults
		    start_test.go:278: 
		        	Error Trace:	/workspace/source/pkg/cmd/start/start_test.go:278
		        	Error:      	Received unexpected error:
		        	            	failed to parse git server URL [https://fake.git:](https://fake.git/) invalid path  could not determine organisation and repository name
		        	Test:       	TestPipelineStart
		        	Messages:   	failed to run command for test defaults
		FAIL
		FAIL	github.com/jenkins-x-plugins/jx-pipeline/pkg/cmd/start	24.256s
```

You can replicate this by running `make test` locally. Please make a PR to fix this ASAP. If you don't I'll revert this PR.

It is is of course weird that the pullrequest pipeline doesn't run the tests. It would be good if you fixed this as well.

**Comment by yelhouti** [comment]
@msvticket on it

**Pull request merged**
