### PR TITLE
fixed argument configureOpts to return git credentials to gitFactory

### PR DESCRIPTION
**Pull request by KiranSatyaRaj**
Signed-off-by: Kiran Satya Raj <kiranjamy20021508@gmail.com>
fixes [jenkins-x/jx#8421](https://github.com/jenkins-x/jx/issues/8421)

### CODE REVIEW

**Comment by KiranSatyaRaj** [comment]
@msvticket there are a few test cases failing when I ran `make lint`
Error:
`-//nolint
+// nolint
 func (p *inliner) processTaskSpec(ts *v1beta1.TaskSpec, path, name string) (bool, error) {
 	templateImage := ""
 	if ts.StepTemplate != nil {
make: *** [Makefile:170: lint] Error 1
`

**Comment by msvticket** [comment]
This is the output of the linter:
```
cmd/docs/main.go:7: File is not `gofmt`-ed with `-s` (gofmt)
//     http://www.apache.org/licenses/LICENSE-2.0
cmd/docs/md_docs.go:7: File is not `gofmt`-ed with `-s` (gofmt)
//     http://www.apache.org/licenses/LICENSE-2.0
pkg/cmd/effective/effective.go:4:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
	"io/ioutil"
	^
```

**Comment by KiranSatyaRaj** [comment]
> hey @msvticket, `make lint` gave me an output to install golangci-lint v1.46.2 just that, I currently have v1.50.1, so should it be update then

hey @msvticket can we discuss this if you're available?

**Comment by msvticket** [comment]
> hey @msvticket, `make lint` gave me an output to install golangci-lint v1.46.2 just that, I currently have v1.50.1, so should it be update then

I suspect that if you have a newer lint you will find more problems. But what you have to fix are the issues that the lint pipeline finds

**Comment by KiranSatyaRaj** [comment]
> > hey @msvticket, `make lint` gave me an output to install golangci-lint v1.46.2 just that, I currently have v1.50.1, so should it be update then
> 
> I suspect that if you have a newer lint you will find more problems. But what you have to fix are the issues that the lint pipeline finds

I've installed the 1.46.2 version of golangci-lint(current version for jx-pipilne), I got a few warns on bodyclose, rowserrcheck, structcheck, unparam are disabled because of go1.18 and an error 
`pkg/cmd/effective/effective.go:4:2: SA1019: package io/ioutil is deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
	"io/ioutil"
`
so all the functions from io/ioutil should be replaced by equivalent functions from io or os packages, right?

**Comment by msvticket** [comment]
@KiranSatyaRaj Why don't you just fix the lint issues in https://github.com/jenkins-x-plugins/jx-pipeline/pull/509#issuecomment-1339730987 ?

**Comment by KiranSatyaRaj** [comment]
hey @msvticket, can you please let me know the command you used to perform lint because I get an output different from [#509 (comment)](https://github.com/jenkins-x-plugins/jx-pipeline/pull/509#issuecomment-1339730987)  when I execute `make lint`

**Pull request closed without merging**
