### PR TITLE
chore: upgrade tektoncd pipeline module to 0.32.4

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

Also upgrades go version to `1.18`

### CODE REVIEW

**Review by rajatgupta24 — APPROVED** [review]
LGTM

**Comment by ankitm123** [comment]
Killed the jobs manually, as they had passed before.

**Comment by ankitm123** [comment]
related to https://github.com/jenkins-x/jx/issues/8283

**Pull request merged**
